package app.babylog.nativeapp;

import android.content.Context;
import android.content.SharedPreferences;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

public final class BabyLogPreVisitQuestionStore {
    private static final String PREF_FILE_NAME = "babylog_pre_visit";
    private static final String QUESTIONS_KEY = "questions";

    private final Context appContext;

    public BabyLogPreVisitQuestionStore(Context context) {
        appContext = context.getApplicationContext();
    }

    public List<Question> listQuestions() {
        JSONArray array = readArray();
        List<Question> questions = new ArrayList<>();
        for (int i = 0; i < array.length(); i++) {
            Question question = Question.fromJson(array.optJSONObject(i));
            if (question != null) {
                questions.add(question);
            }
        }
        return questions;
    }

    public Question saveQuestion(String id, String text, String visitDate) throws JSONException {
        String cleanText = text == null ? "" : text.trim();
        if (cleanText.isEmpty()) {
            throw new JSONException("question text is blank");
        }
        String cleanDate = visitDate == null ? "" : visitDate.trim();
        String now = BabyLogFormatters.nowIso();
        JSONArray current = readArray();
        JSONArray updated = new JSONArray();
        boolean replaced = false;
        Question saved = null;
        String targetId = id == null || id.trim().isEmpty() ? "pvq_" + UUID.randomUUID() : id.trim();
        for (int i = 0; i < current.length(); i++) {
            Question existing = Question.fromJson(current.optJSONObject(i));
            if (existing == null) {
                continue;
            }
            if (targetId.equals(existing.id)) {
                saved = new Question(targetId, cleanText, cleanDate, existing.createdAt, now);
                updated.put(saved.toJson());
                replaced = true;
            } else {
                updated.put(existing.toJson());
            }
        }
        if (!replaced) {
            saved = new Question(targetId, cleanText, cleanDate, now, now);
            updated.put(saved.toJson());
        }
        preferences().edit().putString(QUESTIONS_KEY, updated.toString()).commit();
        return saved;
    }

    public void deleteQuestion(String id) {
        if (id == null || id.trim().isEmpty()) {
            return;
        }
        JSONArray current = readArray();
        JSONArray updated = new JSONArray();
        for (int i = 0; i < current.length(); i++) {
            Question question = Question.fromJson(current.optJSONObject(i));
            if (question == null || id.equals(question.id)) {
                continue;
            }
            try {
                updated.put(question.toJson());
            } catch (JSONException ignored) {
                // Existing stored records are generated by this class; skip malformed rows defensively.
            }
        }
        preferences().edit().putString(QUESTIONS_KEY, updated.toString()).commit();
    }

    private JSONArray readArray() {
        try {
            return new JSONArray(preferences().getString(QUESTIONS_KEY, "[]"));
        } catch (JSONException ignored) {
            return new JSONArray();
        }
    }

    private SharedPreferences preferences() {
        return appContext.getSharedPreferences(PREF_FILE_NAME, Context.MODE_PRIVATE);
    }

    public static final class Question {
        public final String id;
        public final String text;
        public final String visitDate;
        public final String createdAt;
        public final String updatedAt;

        public Question(String id, String text, String visitDate, String createdAt, String updatedAt) {
            this.id = id == null ? "" : id;
            this.text = text == null ? "" : text;
            this.visitDate = visitDate == null ? "" : visitDate;
            this.createdAt = createdAt == null ? "" : createdAt;
            this.updatedAt = updatedAt == null ? "" : updatedAt;
        }

        JSONObject toJson() throws JSONException {
            return new JSONObject()
                    .put("id", id)
                    .put("text", text)
                    .put("visitDate", visitDate)
                    .put("createdAt", createdAt)
                    .put("updatedAt", updatedAt);
        }

        static Question fromJson(JSONObject json) {
            if (json == null) {
                return null;
            }
            String id = json.optString("id", "").trim();
            String text = json.optString("text", "").trim();
            if (id.isEmpty() || text.isEmpty()) {
                return null;
            }
            return new Question(
                    id,
                    text,
                    json.optString("visitDate", "").trim(),
                    json.optString("createdAt", "").trim(),
                    json.optString("updatedAt", "").trim()
            );
        }
    }
}
